version: "3.9"
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass $REDIS_PASSWORD
    ports:
      - "6379:6379"
    volumes:
      - ${PWD}/configs/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - gochat
  gochat:
    build: .
    container_name: gochat
    ports:
      - "8080:8080"
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    depends_on:
      - redis
    networks:
      - gochat
networks:
  gochat:
    driver: bridge
